#!/bin/sh

mandoc -T pdf doc/man/devas-filter.1 > doc/man/devas-filter.pdf
mandoc -T pdf doc/man/devas-visibility.1 > doc/man/devas-visibility.pdf
mandoc -T pdf doc/man/make-coordinates-file.1 > doc/man/make-coordinates-file.pdf
mandoc -T pdf doc/man/devas-visualize-geometry.1 > doc/man/devas-visualize-geometry.pdf
mandoc -T pdf doc/man/devas-compare-boundaries.1 > doc/man/devas-compare-boundaries.pdf
mandoc -T pdf doc/man/luminance-boundaries.1 > doc/man/luminance-boundaries.pdf
mandoc -T pdf doc/man/geometry-boundaries.1 > doc/man/geometry-boundaries.pdf
